### PR TITLE
Bootstrapped frontend

### LINKED ISSUE #7: Bootstrap - frontend
- configure React (maybe Ant)
- Create React App
- application design
-- menu

### LINKED ISSUE #9: Two folders on Github - frontend/backend

### PR DESCRIPTION
**Pull request by Radekowicz**
Please review 💯 
@Fohin 
@Workata 
@FilipJQ77 
@pfedorczak98 
@d-kurowski

### CODE REVIEW

**Comment by FilipJQ77** [comment]
Great job!

**Comment by pfedorczak98** [comment]
Good job!

**Comment by Fohin** [comment]
Looks cool.

**Comment by Workata** [comment]
Look good to me 🥇

**Comment by oleks12345** [comment]
You can use reaction, instead of comments. It's good when you just accept commit

**Pull request merged**
